### ISSUE TITLE
CI build failed.

### ISSUE THREAD

**Issue by isamu** [xkeshi/vue-qrcode#42]
I am using 2.0.0-rc.1 version.
I got an error when building with CI.

```
This dependency was not found:
 ERROR  Build failed with errors.

* qrcode in ./node_modules/@chenfengyuan/vue-qrcode/dist/vue-qrcode.esm.js
```

Is it possible to move the qrcode from devDependencies to dependencies?

**Comment by fengyuanchen** [comment]
That's not good practice. 

Just install it manually: `npm install qrcode @chenfengyuan/vue-qrcode@next`
