### ISSUE TITLE
Vue 3, extract QR image

### ISSUE THREAD

**Issue by ravenshore** [xkeshi/vue-qrcode#43]
Is there an example somewhere on how to extract the QR image from QR generated in template ( perhaps using ref or other means )
I am trying to use the generated QR to insert into email. Thanks!

**Comment by fengyuanchen** [comment]
You can extract the QR code in a `ready` event handler.


```html
<template>
  <vue-qrcode
    value="https://github.com/fengyuanchen"
    tag="img"
    @ready="onReady"
  ></vue-qrcode>
</template>

<script>
export default {
  methods: {
    onReady(image) {
      console.log(image.src);
    },
  },
}
</script>
```
