### ISSUE TITLE
Treat qrcode as dependency rather than peerDependency

### ISSUE THREAD

**Issue by colgin** [xkeshi/vue-qrcode#44]
In version 1.x, qrcode is dependency, but it changed now, it is peerDependency now. I'm really puzzled about what makes this change.
In my opinion, users don't need to install qrcode manually if qrcode is treated as dependency.

**Comment by fengyuanchen** [comment]
For a peer dependency, users can choose the exact version of `qrcode` as they need, just like Vue components don't list `vue` package as a dependency but as a peer dependency.

**Comment by housemeow** [comment]
how about use `overrides` and `resolutions` properties to replace peer dependency?

https://stackoverflow.com/a/64452515
